name: complite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  connectivity_plus: ^7.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  http: ^1.6.0
  logger: ^2.7.0
  logging: ^1.3.0
  retry: ^3.1.2
  riverpod: ^3.2.1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
